/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sig.view;

import com.sig.controller.InvoiceController;
import com.sig.model.InvoiceModel;

/**
 *
 * @author Mohamed Barakat
 */
public class InvoiceForm extends javax.swing.JFrame {
    
        InvoiceController invoiceController;

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
                invoiceController= new InvoiceController(
        new InvoiceModel(),this
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightSidePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        invNumLbl = new javax.swing.JLabel();
        invDateLbl = new javax.swing.JLabel();
        cstNameLbl = new javax.swing.JLabel();
        invTotalLbl = new javax.swing.JLabel();
        itmTablePanel = new javax.swing.JScrollPane();
        itmTable = new javax.swing.JTable();
        saveInvBtn = new javax.swing.JButton();
        cancelInvBtn = new javax.swing.JButton();
        invItmLbl = new javax.swing.JLabel();
        leftSidePanel = new javax.swing.JPanel();
        invTableLbl = new javax.swing.JLabel();
        invTablePanel = new javax.swing.JScrollPane();
        invTable = new javax.swing.JTable();
        createNewInvBtn = new javax.swing.JButton();
        deleteInvBtn = new javax.swing.JButton();
        invMenuBar = new javax.swing.JMenuBar();
        invMenu = new javax.swing.JMenu();
        saveInvFile = new javax.swing.JMenuItem();
        loadInvFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Invoice No.:");

        jLabel12.setText("Invoice Date:");

        jLabel13.setText("Customer Name:");

        jLabel14.setText("Invoice Total:");

        itmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Name", "Price", "Count", "Total"
            }
        ));
        itmTablePanel.setViewportView(itmTable);

        saveInvBtn.setText("Create New Line");
        saveInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInvBtnActionPerformed(evt);
            }
        });

        cancelInvBtn.setText("Delete Line");

        invItmLbl.setText("Invoice Items:");

        javax.swing.GroupLayout rightSidePanelLayout = new javax.swing.GroupLayout(rightSidePanel);
        rightSidePanel.setLayout(rightSidePanelLayout);
        rightSidePanelLayout.setHorizontalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveInvBtn)
                .addGap(91, 91, 91)
                .addComponent(cancelInvBtn)
                .addGap(113, 113, 113))
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(invItmLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itmTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addGroup(rightSidePanelLayout.createSequentialGroup()
                                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(50, 50, 50)
                                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invTotalLbl)
                                    .addComponent(cstNameLbl)
                                    .addComponent(invDateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(invNumLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        rightSidePanelLayout.setVerticalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(invNumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(invDateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cstNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(invTotalLbl))
                .addGap(29, 29, 29)
                .addComponent(invItmLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itmTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveInvBtn)
                    .addComponent(cancelInvBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invTableLbl.setText("Invoice Table:");

        invTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invTable.setColumnSelectionAllowed(true);
        invTablePanel.setViewportView(invTable);
        invTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        createNewInvBtn.setText("Create New Invoice");

        deleteInvBtn.setText("Delete Invoice");
        deleteInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(invTableLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(createNewInvBtn)
                .addGap(66, 66, 66)
                .addComponent(deleteInvBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invTableLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewInvBtn)
                    .addComponent(deleteInvBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invMenu.setText("File");

        saveInvFile.setText("Save");
        saveInvFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInvFileActionPerformed(evt);
            }
        });
        invMenu.add(saveInvFile);

        loadInvFile.setText("Load");
        loadInvFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInvFileActionPerformed(evt);
            }
        });
        invMenu.add(loadInvFile);

        invMenuBar.add(invMenu);

        setJMenuBar(invMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveInvFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInvFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveInvFileActionPerformed

    private void loadInvFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInvFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadInvFileActionPerformed

    private void deleteInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInvBtnActionPerformed

    private void saveInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveInvBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelInvBtn;
    private javax.swing.JButton createNewInvBtn;
    private javax.swing.JLabel cstNameLbl;
    private javax.swing.JButton deleteInvBtn;
    private javax.swing.JLabel invDateLbl;
    private javax.swing.JLabel invItmLbl;
    private javax.swing.JMenu invMenu;
    private javax.swing.JMenuBar invMenuBar;
    private javax.swing.JLabel invNumLbl;
    private javax.swing.JTable invTable;
    private javax.swing.JLabel invTableLbl;
    private javax.swing.JScrollPane invTablePanel;
    private javax.swing.JLabel invTotalLbl;
    private javax.swing.JTable itmTable;
    private javax.swing.JScrollPane itmTablePanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JMenuItem loadInvFile;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JButton saveInvBtn;
    private javax.swing.JMenuItem saveInvFile;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cancelInvBtn
     */
    public javax.swing.JButton getCancelInvBtn() {
        return cancelInvBtn;
    }

    /**
     * @return the createNewInvBtn
     */
    public javax.swing.JButton getCreateNewInvBtn() {
        return createNewInvBtn;
    }

    /**
     * @return the cstNameLbl
     */
    public javax.swing.JLabel getCstNameLbl() {
        return cstNameLbl;
    }

    /**
     * @return the deleteInvBtn
     */
    public javax.swing.JButton getDeleteInvBtn() {
        return deleteInvBtn;
    }

    /**
     * @return the invDateLbl
     */
    public javax.swing.JLabel getInvDateLbl() {
        return invDateLbl;
    }

    /**
     * @return the invItmLbl
     */
    public javax.swing.JLabel getInvItmLbl() {
        return invItmLbl;
    }

    /**
     * @return the invMenu
     */
    public javax.swing.JMenu getInvMenu() {
        return invMenu;
    }

    /**
     * @return the invMenuBar
     */
    public javax.swing.JMenuBar getInvMenuBar() {
        return invMenuBar;
    }

    /**
     * @return the invNumLbl
     */
    public javax.swing.JLabel getInvNumLbl() {
        return invNumLbl;
    }

    /**
     * @return the invTable
     */
    public javax.swing.JTable getInvTable() {
        return invTable;
    }

    /**
     * @return the invTableLbl
     */
    public javax.swing.JLabel getInvTableLbl() {
        return invTableLbl;
    }

    /**
     * @return the invTablePanel
     */
    public javax.swing.JScrollPane getInvTablePanel() {
        return invTablePanel;
    }

    /**
     * @return the invTotalLbl
     */
    public javax.swing.JLabel getInvTotalLbl() {
        return invTotalLbl;
    }

    /**
     * @return the itmTable
     */
    public javax.swing.JTable getItmTable() {
        return itmTable;
    }

    /**
     * @return the loadInvFile
     */
    public javax.swing.JMenuItem getLoadInvFile() {
        return loadInvFile;
    }

    /**
     * @return the saveInvBtn
     */
    public javax.swing.JButton getSaveInvBtn() {
        return saveInvBtn;
    }

    /**
     * @return the saveInvFile
     */
    public javax.swing.JMenuItem getSaveInvFile() {
        return saveInvFile;
    }
}
